version: '3'
services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=distribuidos
      - MONGO_INITDB_ROOT_PASSWORD=Distribuidos1-2023-a-m-r
      - MONGO_INITBD_DATABASE=eonet